# Generated by Django 5.2.1 on 2025-07-23 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de Telefone'),
            preserve_default=False,
        ),
    ]
