# Generated by Django 5.2.1 on 2025-07-23 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_remove_usuario_phonenumber_usuario_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de Telefone'),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='phone_number',
            new_name='telefone',
        ),
    ]
