# Generated by Django 5.2.1 on 2025-07-23 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_alter_usuario_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de Telefone'),
        ),
    ]
