# Generated by Django 5.2.1 on 2025-07-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone',
            new_name='phone_number',
        ),
    ]
