# Generated by Django 5.2.5 on 2025-08-08 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_rename_telefone_usuario_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('book_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Author')),
                ('book_publisher', models.CharField(blank=True, max_length=255, verbose_name='Book Publisher')),
                ('book_publication_date', models.DateField(blank=True, null=True, verbose_name='Book Publication Year')),
                ('book_description', models.TextField(blank=True, null=True, verbose_name='Book Description')),
                ('post_location_city', models.CharField(max_length=100, verbose_name='Post City')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Post Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Creation Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
            ],
        ),
    ]
