# Generated by Django 5.2.5 on 2025-08-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_alter_usuario_email_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
    ]
