# Generated by Django 5.2.4 on 2025-09-01 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0007_remove_usuario_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Número inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de Telefone'),
        ),
    ]
