# Generated by Django 5.2.5 on 2025-09-12 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_publication_full_text_excerpt_publication_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='full_text_excerpt',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='language',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='post_thumbnail',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='Aplicativo.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
