# Generated by Django 5.2.5 on 2025-09-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0010_chatgroup_remove_publication_full_text_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(default='defaults/default_user.png', upload_to='profiles/'),
        ),
    ]
