# Generated by Django 5.2.5 on 2025-09-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0011_usuario_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='full_text_excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='post_thumbnail',
            field=models.ImageField(default='defaults/default_thumbnail.png', upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='favorite_genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_rating', models.IntegerField(blank=True, null=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('messaged_author', models.BooleanField(default=False)),
                ('verified_trade', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'publication')},
            },
        ),
    ]
