# Generated by Django 5.2.5 on 2025-09-15 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0012_publication_full_text_excerpt_publication_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='book_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='publication',
            name='post_type',
            field=models.CharField(choices=[('LOAN', 'Loan'), ('EXCHANGE', 'Exchange')], default='LOAN', max_length=10),
        ),
    ]
