# Generated by Django 5.2.5 on 2025-09-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0013_publication_book_rating_publication_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_type',
            field=models.CharField(choices=[('EMPRESTIMO', 'Emprestimo'), ('TROCA', 'Troca')], default='EMPRESTIMO', max_length=10),
        ),
    ]
