# Generated by Django 5.2.5 on 2025-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0014_alter_publication_post_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
