# Generated by Django 5.2.5 on 2025-09-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0015_alter_usuario_managers_remove_usuario_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Post Author'),
        ),
    ]
