# Generated by Django 5.2.5 on 2025-09-16 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0015_alter_usuario_managers_remove_usuario_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='post_thumbnail',
            new_name='post_cover',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='post_creator',
        ),
    ]
