# Generated by Django 5.2.5 on 2025-09-16 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0016_rename_post_thumbnail_publication_post_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Post Author'),
        ),
    ]
