# Generated by Django 5.2.5 on 2025-09-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0018_remove_usuario_nome_remove_usuario_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created',
            new_name='created_at',
        ),
    ]
