# Generated by Django 5.2.5 on 2025-09-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0019_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='created_at',
            new_name='created',
        ),
    ]
