# Generated by Django 5.2.5 on 2025-09-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0020_rename_created_at_publication_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='is_liked',
            new_name='is_saved',
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_type',
            field=models.CharField(choices=[('emprestimo', 'Empréstimo'), ('troca', 'Troca')], default='emprestimo', max_length=10),
        ),
    ]
