# Generated by Django 5.2.5 on 2025-09-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0021_alter_publication_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='post_type',
        ),
    ]
