# Generated by Django 5.2.5 on 2025-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0022_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
