# Generated by Django 5.2.5 on 2025-09-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0022_remove_publication_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='post_type',
            field=models.CharField(choices=[('emprestimo', 'Empréstimo'), ('troca', 'Troca')], default='emprestimo', max_length=10),
        ),
    ]
