# Generated by Django 5.2.5 on 2025-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0023_interaction_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
