# Generated by Django 5.2.5 on 2025-09-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0025_alter_interaction_publication_alter_interaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='created',
            new_name='created_at',
        ),
    ]
