# Generated by Django 5.2.5 on 2025-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0026_rename_created_publication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
