# Generated by Django 5.2.5 on 2025-09-24 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0027_alter_interaction_saved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('completed', 'Finalizado'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL, verbose_name='Quem pegou emprestado')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_books', to=settings.AUTH_USER_MODEL, verbose_name='Quem emprestou')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='Aplicativo.publication')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BookCareRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de cuidado (1-5)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentários sobre o estado do livro')),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_rating', to='Aplicativo.loan')),
            ],
        ),
    ]
