# Generated by Django 5.2.5 on 2025-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0028_loan_bookcarerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
