# Generated by Django 5.2.5 on 2025-09-25 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0029_usuario_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Post Author'),
            preserve_default=False,
        ),
    ]
