# Generated by Django 5.2.5 on 2025-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0030_alter_publication_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='book_genre',
            field=models.CharField(blank=True, choices=[('romance_narrativa', 'Romance/Narrativa'), ('poesia', 'Poesia'), ('peca_teatral', 'Peça Teatral'), ('didatico', 'Didático'), ('nao_ficcao', 'Não-ficção')], max_length=20, null=True, verbose_name='Gênero do Livro'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_location_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post City'),
        ),
    ]
