# Generated by Django 5.2.5 on 2025-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0031_publication_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cluster_label',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cluster_label',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Publisher'),
        ),
    ]
