# Generated by Django 5.2.5 on 2025-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0032_publication_cluster_label_usuario_cluster_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
