# Generated by Django 5.2.5 on 2025-10-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0033_publication_is_fake_usuario_is_fake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='preferred_genres',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
