# Generated by Django 5.2.5 on 2025-10-02 17:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0035_usuario_book_care_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=396, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=396, null=True),
        ),
    ]
