# Generated by Django 5.2.5 on 2025-10-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0035_userstats_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='user_rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
