# Generated by Django 5.2.5 on 2025-10-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0035_usuario_book_care_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_cover',
            field=models.ImageField(blank=True, default='defaults/default_thumbnail.png', null=True, upload_to='livros/'),
        ),
    ]
