# Generated by Django 5.2.5 on 2025-10-03 15:34

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0036_publication_embedding_usuario_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='preferred_genres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
