# Generated by Django 5.2.5 on 2025-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0036_userrating_user_rating_userstats_total_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='book_care_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='person_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='total_book_care_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='total_person_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='total_user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
