# Generated by Django 5.2.5 on 2025-10-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0037_usuario_book_care_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
