# Generated by Django 5.2.5 on 2025-10-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0037_alter_usuario_preferred_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
