# Generated by Django 5.2.5 on 2025-10-05 22:44

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0038_alter_publication_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='full_text_excerpt',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_genre',
            field=models.CharField(choices=[('romance_narrativa', 'Romance/Narrativa'), ('poesia', 'Poesia'), ('peca_teatral', 'Peça Teatral'), ('didatico', 'Didático'), ('nao_ficcao', 'Não-ficção'), ('nao_especificado', 'Não especificado')], default='nao_especificado', max_length=20, verbose_name='Gênero do Livro'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='embedding',
        ),
        migrations.AddField(
            model_name='publication',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=397, null=True),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='embedding',
        ),
        migrations.AddField(
            model_name='usuario',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=397, null=True),
        ),
    ]
