# Generated by Django 5.2.5 on 2025-10-06 14:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0039_remove_publication_full_text_excerpt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='embedding',
            new_name='full_vector',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='embedding',
            new_name='full_vector',
        ),
        migrations.AddField(
            model_name='publication',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='features_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=13, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='features_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=13, null=True),
        ),
    ]
