# Generated by Django 5.2.5 on 2025-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0039_remove_publication_full_text_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
