# Generated by Django 5.2.5 on 2025-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0040_rename_embedding_publication_full_vector_and_more'),
        ('Aplicativo', '0040_usuario_is_online_usuario_last_seen'),
    ]

    operations = [
    ]
