# Generated by Django 5.2.5 on 2025-10-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0036_alter_publication_post_cover'),
        ('Aplicativo', '0041_merge_20251006_1132'),
    ]

    operations = [
    ]
