# Generated by Django 5.2.5 on 2025-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0042_merge_20251006_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_cover',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
