# Generated by Django 5.2.5 on 2025-10-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0043_alter_publication_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
