# Generated by Django 5.2.5 on 2025-10-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0042_merge_20251006_1641'),
        ('Aplicativo', '0044_publication_is_available'),
    ]

    operations = [
    ]
