# Generated by Django 5.2.5 on 2025-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0045_merge_20251007_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='updt_feat_vec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='updt_text_vec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updt_feat_vec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updt_text_vec',
            field=models.BooleanField(default=False),
        ),
    ]
