# Generated by Django 5.2.5 on 2025-10-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0045_merge_20251007_1102'),
        ('Aplicativo', '0046_publication_updt_feat_vec_publication_updt_text_vec_and_more'),
    ]

    operations = [
    ]
