# Generated by Django 5.2.5 on 2025-10-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0045_merge_20251007_0826'),
        ('Aplicativo', '0047_merge_20251007_1358'),
    ]

    operations = [
    ]
