# Generated by Django 5.2.5 on 2025-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0048_merge_20251007_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='updt_feat_vec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='updt_text_vec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updt_feat_vec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updt_text_vec',
            field=models.BooleanField(default=True),
        ),
    ]
