# Generated by Django 5.2.5 on 2025-10-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0047_merge_20251008_1041'),
        ('Aplicativo', '0049_alter_publication_updt_feat_vec_and_more'),
    ]

    operations = [
    ]
