# Generated by Django 5.2.5 on 2025-10-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0050_merge_20251008_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInteractionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cluster_id', models.IntegerField()),
                ('publication_cluster_id', models.IntegerField()),
                ('interaction_strength', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_cluster_id', 'publication_cluster_id')},
            },
        ),
    ]
